export const TASK_MANAGEMENT_LIST = [
  {
    title: `Design Homepage Layout`,
    description: `Create initial mockups for homepage design`,
    status: `In Progress`,
    type: `Design`,
    dueDate: `2025-10-25`,
    assignee: `Alice`,
    urgency: `High`,
  },
  {
    title: `Write Product Descriptions`,
    description: `Write SEO-friendly descriptions for 10 new products`,
    status: `New`,
    type: `Content`,
    dueDate: `2025-10-22`,
    assignee: `Bob`,
    urgency: `Medium`,
  },
  {
    title: `Backend API Testing`,
    description: `Run integration tests on user authentication endpoints`,
    status: `In Progress`,
    type: `Development`,
    dueDate: `2025-10-21`,
    assignee: `Alice`,
    urgency: `High`,
  },
  {
    title: `Update Privacy Policy`,
    description: `Revise privacy policy for new GDPR compliance`,
    status: `Completed`,
    type: `Legal`,
    dueDate: `2025-10-15`,
    assignee: `David`,
    urgency: `Low`,
  },
  {
    title: `Set Up Email Campaign`,
    description: `Create and schedule October promotional email blast`,
    status: `Reviewing`,
    type: `Marketing`,
    dueDate: `2025-10-19`,
    assignee: `Alice`,
    urgency: `High`,
  },
  {
    title: `Client Feedback Summary`,
    description: `Compile and summarize client feedback from Q3`,
    status: `New`,
    type: `Reporting`,
    dueDate: `2025-10-24`,
    assignee: `Frank`,
    urgency: `Medium`,
  },
  {
    title: `Security Audit`,
    description: `Perform vulnerability assessment on production servers`,
    status: `In Progress`,
    type: `IT`,
    dueDate: `2025-10-23`,
    assignee: `Alice`,
    urgency: `High`,
  },
  {
    title: `Employee Onboarding Docs`,
    description: `Update onboarding materials for new hires`,
    status: `New`,
    type: `HR`,
    dueDate: `2025-10-28`,
    assignee: `Helen`,
    urgency: `Medium`,
  },
  {
    title: `App Store Listing Update`,
    description: `Refresh screenshots and description on app store`,
    status: `Completed`,
    type: `Marketing`,
    dueDate: `2025-10-10`,
    assignee: `Ian`,
    urgency: `Low`,
  },
  {
    title: `Prepare Budget Report`,
    description: `Draft Q4 budget projection and expense summary`,
    status: `In Progress`,
    type: `Finance`,
    dueDate: `2025-10-20`,
    assignee: `John`,
    urgency: `High`,
  },
  {
    title: `Migrate Database`,
    description: `Move production database to new cloud provider`,
    status: `New`,
    type: `Development`,
    dueDate: `2025-10-27`,
    assignee: `Kate`,
    urgency: `High`,
  },
  {
    title: `Create Social Media Calendar`,
    description: `Plan content schedule for November posts`,
    status: `Reviewing`,
    type: `Marketing`,
    dueDate: `2025-10-22`,
    assignee: `Noah`,
    urgency: `Medium`,
  },
  {
    title: `Update Support FAQs`,
    description: `Add new entries for recent customer issues`,
    status: `Completed`,
    type: `Customer Support`,
    dueDate: `2025-10-16`,
    assignee: `Mia`,
    urgency: `Low`,
  },
  {
    title: `Website Performance Optimization`,
    description: `Improve page load speed and image compression`,
    status: `In Progress`,
    type: `Development`,
    dueDate: `2025-10-26`,
    assignee: `Noah`,
    urgency: `High`,
  },
  {
    title: `Conduct Team Retrospective`,
    description: `Schedule and run sprint retrospective meeting`,
    status: `New`,
    type: `Management`,
    dueDate: `2025-10-20`,
    assignee: `Bob`,
    urgency: `Medium`,
  },
];
